version: "3.8"

services:
  # API de détection de fraude
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models # Pour que l'API accède aux modèles entraînés
    networks:
      - mlops-network

  # Prometheus : La base de données de métriques
  prometheus:
    image: prom/prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mlops-network

  # Grafana : La visualisation (Dashboard)
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge
    
volumes:
  prometheus_data:
  grafana_data:    